version: "3.7"
services:
  db:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    expose:
      - '5432'
  web:
    image: hotwire_web:latest
    build: 
      context: .
      args:
        BUNDLE_PATH: /bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      RAILS_ENV: development
      BUNDLE_PATH: /bundle
      GEM_HOME: /bundle
      GEM_PATH: /bundle
    volumes:
      - .:/hotwire
      - bundle:/bundle
      - node_modules:/hotwire/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "db"

  css:
    image: hotwire_web:latest
    depends_on:
      - "web"
    command: yarn build:css --watch

  js:
    image: hotwire_web:latest
    depends_on:
      - "web"
    command: yarn build --watch
    tty: true

volumes:
  db:
  bundle:
  node_modules: