services: 
  postgres:
    image: postgres:13-alpine
    env_file: .env.dev
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "15431:5432"

  redis:
    image: redis:7.0-alpine
    ports:
      - "16379:6379"
    volumes:
      - "redis_data:/data"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "4000:3000"
    depends_on:
      postgres:
        condition: "service_started"
      redis:
        condition: "service_started"
    env_file: .env.dev
    volumes:
      - .:/rails
      - app-storage:/rails/storage
      - bundle:/rails/vendor/bundle
      - node_modules:/rails/node_modules

volumes:
  postgres_data: {}
  redis_data: {}
  app-storage: {}
  bundle: {}
  node_modules: {}
