version: "3.7"
services:
  db:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    expose:
      - '5432'
  redis:
    image: 'redis:6.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    &web
    build: 
      context: .
      args:
        BUNDLE_PATH: /bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      RAILS_ENV: development
      BUNDLE_PATH: /bundle
      GEM_HOME: /bundle
      GEM_PATH: /bundle
    volumes:
      - .:/hotwire
      - bundle:/bundle
      - node_modules:/hotwire/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"

  css:
    <<: *web
    command: yarn build:css --watch
    ports:
      - "3035:3035"

  js:
    <<: *web
    tty: true
    command: yarn build --watch
    ports:
      - "3040:3040"


volumes:
  db:
  bundle:
  node_modules: