version: "3.7"
services:
  db:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    expose:
      - '5432'
  web:
    &web
    build: 
      context: .
      args:
        BUNDLE_PATH: /bundle
    # command: /hotwire/bin/dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      RAILS_ENV: development
      BUNDLE_PATH: /bundle
      GEM_HOME: /bundle
      GEM_PATH: /bundle
    volumes:
      - .:/hotwire
      - bundle:/bundle
      - node_modules:/hotwire/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      # - "css"
      # - "js"

  css:
    <<: *web
    command: yarn build:css --watch
    ports:
      - "3035:3035"
  #   build: 
  #     context: .
  #   command: yarn build:css --watch
  #   depends_on:
  #     - "db"
  js:
    <<: *web
    command: yarn build --watch
    ports:
      - "3036:3036"
  # js:
  #   build: 
  #     context: .
  #   command: yarn build --watch
  #   depends_on:
  #     - "db"

volumes:
  db:
  bundle:
  node_modules: