service: hotwire
image: dielume/hotwire

servers:
  web:
    - 128.199.13.238

registry:
  username: dielume
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 128.199.13.238

    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    PT_SILENCE_AR_COMPAT_WARNING: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  redis:
    image: redis:6.2.4
    host: 128.199.13.238
    port: 6379
    env:
      directories:
        - data:/data

  db:
    image: postgres:13.3
    host: 128.199.13.238
    port: 5432
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: hotwire_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
