service: hotwire
image: dielume/hotwire

servers:
  web:
    hosts:
      - 65.109.131.207
    options:
      network: 'kamal_network'
    labels:
      traefik.http.routers.hotwire.entrypoints: websecure
      traefik.http.routers.hotwire.rule: Host(`kamal.website`)
      traefik.http.routers.hotwire.tls: true
      traefik.http.routers.hotwire.tls.certresolver: letsencrypt

  sidekiq:
    hosts:
      - 65.109.131.207
    cmd: bundle exec sidekiq -C config/sidekiq.yml
    options:
      network: 'kamal_network'

builder:
  remote: ssh://root@65.109.131.207
  arch:
    - amd64
    # host: ssh://root@65.109.131.207

# traefik:
#   options:
#     network: 'kamal_network'
#     publish:
#       - '443:443'
#     volume:
#       - '/letsencrypt/acme.json:/letsencrypt/acme.json'
#   args:
#     entryPoints.web.address: ':80'
#     entryPoints.websecure.address: ':443'
#     entryPoints.web.http.redirections.entryPoint.to: websecure
#     entryPoints.web.http.redirections.entryPoint.scheme: https
#     entryPoints.web.http.redirections.entrypoint.permanent: true
#     certificatesResolvers.letsencrypt.acme.email: 'diego.lume.a@gmail.com'
#     certificatesResolvers.letsencrypt.acme.storage: '/letsencrypt/acme.json'
#     certificatesResolvers.letsencrypt.acme.httpchallenge: true
#     certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

registry:
  username: dielume
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    PT_SILENCE_AR_COMPAT_WARNING: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL
    - DB_HOST

accessories:
  redis:
    image: redis:6.2.4
    host: 65.109.131.207
    port: 127.0.0.1:6379:6379
    options:
      network: 'kamal_network'
    env:
      directories: 'data:/data'

  db:
    image: postgres:13.3
    host: 65.109.131.207
    port: 127.0.0.1:5432:5432
    options:
      network: 'kamal_network'
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: hotwire_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
