service: hotwire
image: dielume/hotwire

servers:
  web:
    hosts: 146.190.149.32
    options:
      network: 'kamal_network'
    labels:
      traefik.http.routers.kiqr_cloud.rule: Host(`kamal.website`)
      traefik.http.routers.kiqr_cloud_secure.entrypoints: websecure
      traefik.http.routers.kiqr_cloud_secure.rule: Host(`kamal.website`)
      traefik.http.routers.kiqr_cloud_secure.tls: true
      traefik.http.routers.kiqr_cloud_secure.tls.certresolver: letsencrypt

traefik:
  options:
    network: 'kamal_network'
    publish:
      - '443:443'
    volume:
      - '/letsencrypt/acme.json:/letsencrypt/acme.json'
  args:
    entryPoints.web.address: ':80'
    entryPoints.websecure.address: ':443'
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: 'diego.lume.a@gmail.com'
    certificatesResolvers.letsencrypt.acme.storage: '/letsencrypt/acme.json'
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

registry:
  username: dielume
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    PT_SILENCE_AR_COMPAT_WARNING: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL
    - DB_HOST

accessories:
  redis:
    image: redis:6.2.4
    host: 146.190.149.32
    port: 6379
    options:
      network: 'kamal_network'
    env:
      directories:
        - data:/data

  db:
    image: postgres:13.3
    host: 146.190.149.32
    port: 5432
    options:
      network: 'kamal_network'
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: hotwire_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
